updated bin to current working copy

diff --git a/grake_url b/grake_url
--- a/grake_url
+++ b/grake_url
@@ -1,5 +1,6 @@
 #!/usr/bin/sh
 ## pdq@archlinux
+## Part of FlashSucks 0.0.2
 ## 08-04-2013
 
 ## can be used in firefox with addon Open With 5.3.1 https://addons.mozilla.org/en-US/firefox/addon/open-with/
@@ -16,6 +17,9 @@ elif [ ! -f /usr/bin/xclip ]; then
 elif [ ! -f /usr/bin/vlc ]; then
 	echo "Missing package: vlc [A multi-platform MPEG, VCD/DVD, and DivX player]"
 	exit 1
+elif [ ! -f /usr/bin/zenity ]; then
+	echo "Missing package: zenity [Display graphical dialog boxes from shell scripts]"
+	exit 1
 fi
 
 if [ "$1" != "" ]; then
@@ -27,6 +31,21 @@ if [ "$1" != "" ]; then
 		RES=$(zenity --list --radiolist --width 200 --height 230 --text "Flash sucks" --title="Play video in VLC" --column "Choice" --column "Resolution" TRUE 240p  FALSE 480p FALSE 720p FALSE 1080p)
 		_USEPROX=$([ "$_PROXY" == "Yes" ] && echo "--http-proxy=127.0.0.1:8118 " || echo "")
 		grake -q --proxy="http://127.0.0.1:8118" "$1" | vlc $_USEPROX--preferred-resolution="$RES" -
+			_ACTION=$(zenity --list --radiolist --width 230 --height 230 --text "Flash sucks" --title="Rate, Favorite or Subscribe" --column "Choice" --column "Action" FALSE Nothing TRUE Like FALSE Dislike FALSE Favorite FALSE Subscribe)
+		_DOACTION=
+		if [ "$_ACTION" == "Like" ]; then
+			_DOACTION="--like='$1'"
+		elif [ "$_ACTION" == "Dislike" ]; then
+			_DOACTION="--dislike='$1'"
+		elif [ "$_ACTION" == "Favorite" ]; then
+			_DOACTION="--favorite='$1'"
+		elif [ "$_ACTION" == "Subscribe" ]; then
+			_DOACTION="--subscribe='$1'"
+		fi
+
+		if [ ! -z "$_DOACTION" ]; then
+			zenity --info --text "$(youtube-viewer --prefer-https --noI $_DOACTION)"
+		fi
 	fi
 fi
 
